# Generated by Django 5.2.17 on 2026-08-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titel')),
                ('slug', models.SlugField(blank=True, help_text='Wordt automatisch van de titel gemaakt. Verandert daarna niet meer mee met de titel, zodat gedeelde links blijven werken.', max_length=200, unique=True, verbose_name='URL-naam')),
                ('status', models.CharField(choices=[('draft', 'Concept'), ('published', 'Gepubliceerd')], default='draft', help_text='Alleen een gepubliceerd recept is zichtbaar voor bezoekers.', max_length=20, verbose_name='publicatiestatus')),
            ],
            options={
                'verbose_name': 'recept',
                'verbose_name_plural': 'recepten',
            },
        ),
    ]
