# Generated by Django 5.2.17 on 2026-08-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Zoals je het in de supermarkt koopt: 'Rode paprika', niet 'Paprika'; 'Verse peterselie' en 'Gedroogde peterselie' apart. Twijfel je, kies dan het fijnere niveau (ADR-0007). Een basisingrediënt heet zoals je het in een stap zegt: 'Zout'.", max_length=100, unique=True, verbose_name='naam')),
                ('slug', models.SlugField(blank=True, help_text='Wordt automatisch van de naam gemaakt. Verandert daarna niet meer mee met de naam, zodat gedeelde links blijven werken.', max_length=100, unique=True, verbose_name='URL-naam')),
                ('is_staple', models.BooleanField(default=False, help_text='Staat al in de keuken -- zout, peper, zonnebloemolie, gedroogde kruiden. Wordt op het recept apart van de boodschappen getoond.', verbose_name='basisingrediënt')),
            ],
            options={
                'verbose_name': 'ingrediënt',
                'verbose_name_plural': 'ingrediënten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text="Een getal, zodat het later mee kan schalen met de porties. Leeg laten mag: 'peper' met de opmerking 'naar smaak'.", max_digits=7, null=True, verbose_name='hoeveelheid')),
                ('unit', models.CharField(blank=True, choices=[('gram', 'gram'), ('kilogram', 'kilogram'), ('milliliter', 'milliliter'), ('liter', 'liter'), ('tablespoon', 'eetlepel'), ('teaspoon', 'theelepel'), ('pinch', 'snufje'), ('piece', 'stuk'), ('clove', 'teen'), ('can', 'blik'), ('jar', 'pot'), ('pack', 'pak'), ('bunch', 'bos')], help_text="Leeg laten als de hoeveelheid al genoeg zegt: '2 uien'.", max_length=20, verbose_name='eenheid')),
                ('note', models.CharField(blank=True, help_text="Wat er nog bij hoort: 'van 400gr', 'geraspt', 'fijngesneden'.", max_length=200, verbose_name='opmerking')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lage nummers staan bovenaan op het recept.', verbose_name='volgorde')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='recipes.ingredient', verbose_name='ingrediënt')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_lines', to='recipes.recipe', verbose_name='recept')),
            ],
            options={
                'verbose_name': 'ingrediëntregel',
                'verbose_name_plural': 'ingrediëntregels',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
