# Generated by Django 5.2.17 on 2026-08-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Doorlopend over het hele recept. Een nieuwe fase telt gewoon door en begint niet opnieuw bij 1.', verbose_name='volgorde')),
                ('phase', models.CharField(blank=True, help_text="De kop waar deze stap onder hoort: 'Mise en place', 'Bouwen'. Stappen die op elkaar volgen en dezelfde fase hebben, komen onder één kop te staan. Leeg laten mag.", max_length=100, verbose_name='fase')),
                ('text', models.TextField(help_text='Eén handeling, geschreven voor iemand die jouw keuken niet kent.', verbose_name='stap')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe', verbose_name='recept')),
            ],
            options={
                'verbose_name': 'stap',
                'verbose_name_plural': 'stappen',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
