# Generated by Django 5.2.17 on 2026-08-17 18:34

import django.core.validators
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ook in minuten, en ook leeg als er niets gekookt wordt. De totale tijd wordt hiervan opgeteld en vul je dus nergens in.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='kooktijd'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'makkelijk'), ('medium', 'gemiddeld'), ('hard', 'moeilijk')], max_length=20, verbose_name='moeilijkheidsgraad'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dish_types',
            field=recipes.models.ChoiceArrayField(base_field=models.CharField(choices=[('breakfast', 'ontbijt'), ('lunch', 'lunch'), ('starter', 'voorgerecht'), ('main', 'hoofdgerecht'), ('side', 'bijgerecht'), ('dessert', 'nagerecht'), ('soup', 'soep'), ('salad', 'salade'), ('snack', 'borrelhap'), ('sauce', 'saus')], max_length=20), blank=True, default=list, help_text='Meer dan één mag: een quesadilla is lunch én hoofdgerecht.', size=None, verbose_name='gerechtstype'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text="In minuten, als getal: 20, niet '20 minuten'. De pagina maakt er zelf '20 minuten' of '1 uur 30 minuten' van. Niet van toepassing? Laat leeg -- 0 is geen tijd.", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='bereidingstijd'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='seasons',
            field=recipes.models.ChoiceArrayField(base_field=models.CharField(choices=[('spring', 'lente'), ('summer', 'zomer'), ('autumn', 'herfst'), ('winter', 'winter')], max_length=20), blank=True, default=list, help_text='Alle vier aankruisen betekent: het hele jaar door.', size=None, verbose_name='seizoen'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Voor hoeveel mensen de ingrediëntregels bedoeld zijn.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='porties'),
        ),
    ]
